<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

// This file handles single entries, but only exists for the sake of child theme forward compatibility.

get_header();

do_action('genesis_before_content_sidebar_wrap');
$page = get_posts( array(
    'name'      => 'rentals',
    'post_type' => 'page') );

if ( $page )
{
    echo $page[0]->post_content;
}
?>
<br />
<br />
<div id="rental-container">
    <?php
    $categories = get_terms("rental_category", array("hide_empty" => 0));
    $taxonomy_images = get_option( 'taxonomy_image_plugin' );
    if (count($categories) > 0) :
        foreach ($categories as $category) :// Get the array of Term ID/Image ID pairs

            $attachment_id = $taxonomy_images[$category->term_id]; // Image ID
            $image = wp_get_attachment_image( $attachment_id, 'small');
            ?>
            <a href="<?php echo get_term_link($category->term_id); ?>" class='rental'>
                <div class="thumbnail-container">
                    <div class="thumbnail-overlay"></div>
                    <?php echo $image; ?>
                </div>
                <h3><?php echo $category->name; ?></h3>
            </a>
            <?php
        endforeach;
    endif;
    ?>
</div>
<?php
do_action('genesis_after_content_sidebar_wrap');
get_footer();
?>

