<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/F
 */

// This file handles single entries, but only exists for the sake of child theme forward compatibility.

get_header();
$post = get_post();
do_action('genesis_before_content_sidebar_wrap');

$attributes = get_post_meta($post->ID, "rentals-attributes-list", true);

$encodedAttachments = get_post_meta($post->ID, "attachments", true);
$attachments = json_decode($encodedAttachments);
$attachmentsExist = $attachments->my_attachments !== null;

?>
<div class="swiper-container">
    <!-- Additional required wrapper -->
    <div class="swiper-wrapper">
        <?php
        if ($attachmentsExist):
            foreach ($attachments->my_attachments as $image): ?>
                <div class="swiper-slide">
                   <?php echo wp_get_attachment_image(  $image->id, $size = 'large') ?>
                </div>
            <?php endforeach;
        endif; ?>
    </div>

    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>

    <div class="swiper-pagination"></div>
</div>
<div class="rental-details">
    <h1><?php echo $post->post_title ?></h1>
    <div id="rental-content">
        <?php /* echo do_shortcode("[addthis tool=\"addthis_inline_share_toolbox_rys6\"]"); */ ?>
        <?php the_content(); ?>
    </div>
    <table>
        <?php
        if( $attributes ):
            foreach($attributes as $attribute) :
                $attribute = explode("|", $attribute['rental-attribute']);
        ?>
                <tr>
                    <td><?php echo $attribute[0] ?></td>
                    <td><?php echo $attribute[1] ?></td>
                </tr>
        <?php
            endforeach;
        else :
        endif;
        ?>
    </table>
</div>
<?php
do_action('genesis_after_content_sidebar_wrap');
get_footer();
?>

