<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

// This file handles single entries, but only exists for the sake of child theme forward compatibility.

get_header();

do_action('genesis_before_content_sidebar_wrap');

?>
<div><?php the_archive_description(); ?></div>
<div id="rental-container" class="rental-container-archive">
    <?php while (have_posts()) : the_post();
        $post = get_post();
        $attachments = get_post_meta($post->ID, 'attachments', true);
        $firstAttachmentId = $attachments !== null ? json_decode($attachments)->my_attachments[0]->id : 0;
        $image = wp_get_attachment_image( $firstAttachmentId, 'small');
        ?>
        <div class="single-rental-container">
            <a style="display:block;margin-bottom:20px;" class="single-rental hvr-reveal"
               href="<?php echo get_permalink($post->ID); ?>">
                <?php echo $image ?>
                <h3><?php echo $post->post_title; ?></h3>
            </a>
        </div>
    <?php endwhile; ?>
</div>
<?php
do_action('genesis_after_content_sidebar_wrap');
get_footer();
?>


